Issue 1
danilobjr/notes pull request #4
Opened 2017-08-20 20:53 UTC by nelsoneldoro

Tive problemas em colocar o estilo na div mais externa. Não sei o porque não consegui utilizar o objeto wrapperStyle
![screen shot 2017-08-20 at 17 52 52](https://user-images.githubusercontent.com/137902/29498350-70325cd0-85d0-11e7-935d-1ce79d4fd1bd.png)
.

Tentei fazer uma lista de Cards já deixar o caminho mais fácil para a próxima tarefa mas estava meio perdido então deixei a lista de cards para depois.

2017-08-20 20:55 UTC, nelsoneldoro commented on src/pages/index.tsx
> +        <div style={{display: 'flex', flexDirection: 'column'}}>
ao utilizar o objeto wrapperStyle dava erro

2017-08-21 20:09 UTC, danilobjr commented
@nelsoneldoro Tu pode tipar com a interface `CSSProperties`. Por exemplo:

```typescript
import {CSSProperties} from 'react';

const styles = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
  } as CSSProperties,
};

export default class Index extends Component<{}, {}> {
  render() {
    return (
        <div style={styles.wrapper}>
```

Isso deve resolver o problema.

2017-08-22 12:53 UTC, danilobjr requested changes
@nelsoneldoro Algumas coisas pra gente fechar esse PR e pra vc tb conhecer melhor tais coisas. Ah, subi um commit adicionando alguns estilos globais e locais. Faz um pull.

Os pontos sao:

- [ ] Corrigir inconsistencias apontadas pelo `tslint`.
- [ ] Commitar a exclusao do transpilado `pages/index.js`

Tu pode ir clicando nesses checkes quando cada um for feito pra tu ter um controle e eu tambem. La na issue tambem tem esses checks. Essa checagem reflete la no card de WIP.

Mais alguns itens abaixo.

2017-08-22 12:53 UTC, danilobjr commented on src/pages/index.tsx
> +import {Component} from 'react';
- [ ] Imports de uma mesma lib numa mesma linha, quando possivel.

```typescript
import {Component, CSSProperties} from 'react';
```

2017-08-22 12:53 UTC, danilobjr commented on src/pages/index.tsx
> +class CardModel {
- [ ] Usar interface pra models ao inves de classe.

```typescript
interface Card {
  id: number;
  title: string;
  text: string;
}
```

2017-08-22 12:53 UTC, danilobjr commented on src/pages/index.tsx
> +      new CardModel(1, "Example title1asd", "Example Content"),
- [ ] Usar objetos literais sempre que possivel ao inves de instanciar classes. Afinal, typescript eh javascript. :)

```typescript
{id: 1, title: 'Example title', text: 'Example content'},
```

2017-08-22 12:53 UTC, danilobjr commented on src/pages/index.tsx
> +          {cards.map(c => <Card key={c.id} style={styles.card} title={c.title}>{c.text}</Card>)}
- [ ] Devido ao uso constante de chaves `{}` no TSX, sempre que tiver mais de 2 props ou 2 props e um children, colocar uma prop por linha.

```tsx
{cards.map(c => (
  <Card
    key={c.id}
    style={styles.card}
    title={c.title}
  >
    {c.text}
  </Card>
)}
```

2017-08-22 13:33 UTC, danilobjr commented
@nelsoneldoro Esqueci de mencionar. Vamos passar a usar esse padrao de commit messages

http://karma-runner.github.io/1.0/dev/git-commit-msg.html

2017-08-23 01:20 UTC, danilobjr approved these changes

2017-08-23 02:02 UTC, merged