Issue 2
danilobjr/notes pull request #5
Opened 2017-08-24 01:25 UTC by nelsoneldoro

Criei uma pasta chamada types para colocar a interface CardModel.
Separei a listagem em um componente stateless.
Nomeei alguns arquivos com traço(-). Não sei se o padrão é camelcase.

2017-08-24 23:48 UTC, danilobjr requested changes
@nelsoneldoro Isso ai, cara. Ta funcionando de boa.

Boa sacada de colocar as listagem em um component separado e tambem ter refatorado, extraido o modelo pro seu proprio arquivo. 

Agora alguns pontos de melhoria.

- Tenta dar uma olhada se consegue resolver o problema do _tslint_. Tem varios erros de lint e indentacao aqui no codigo. Faz um deadline curto pra resolver isso. Se nao resolver, avanca pra algo mais util.

Outros pontos abaixo.

_Obs.: subi alguns commits no branch._

2017-08-24 23:48 UTC, danilobjr commented on src/components/card-list.tsx
> +export const CardList: SFC<Props> = ({cards}) => (
Como tu mencionou ali em cima sobre o nome de arquivos. Deixa igual ao nome da classe: `CardList`.

2017-08-24 23:48 UTC, danilobjr commented on src/pages/index.tsx
> +    this.setState({filteredCards});
Aqui vc poderia criar uma prop no state chamada `filter: string;`. Dai essa filtragem dos cards seria algo feito no `render()`:

```tsx
render() {
  // ...
  <CardList cards={this.getFilteredCards()} />
}

getFilteredCards = () => {
  const {cards, filter} = this.state;

  return cards.filter((card) => {
    return card.title.toUpperCase().includes(filter);
  });
}
```

Lembra que React eh declarativo e o state pode ser mais simples. Dai a UI pode ser inteligente pra se comportar de forma complexa diante de pequenas mudancas.

2017-08-24 23:48 UTC, danilobjr commented on src/pages/index.tsx
> +          leftElement={<Icon style={styles.icon}
Essa indentacao estah um pouco confusa. Seria melhor 1 prop por linha.

2017-08-24 23:48 UTC, danilobjr commented on src/pages/index.tsx
>    state: State = {
Aqui seria melhor manter a prop `cards`. E jogar esses dados em um arquivo JSON e pegar tudo de la via `fetch()`. Simulando uma ajax request.

Dai vc faz o `setState` dos cards em `componentDidMount`. Pra nao quebrar a aplicacao seta o estado inicial de cards como sendo `[]`.

```ts
state: State = {
  cards: [],
}

componentDidMount() {
  const cards = fetch(...);
  this.setState({cards});
}

2017-08-24 23:48 UTC, danilobjr commented on src/types/card-model.tsx
> +export interface CardModel {
Pode mudar o nome aqui tambem, do arquivo.
E uma sugestao de nome pra esse modelo: `Note`. O que acha?

2017-08-25 01:18 UTC, nelsoneldoro commented on src/pages/index.tsx
> +    this.setState({filteredCards});
Muito melhor! Inconscientemente fiquei com pena de criar mais propriedades no state e aquelas duas listas no state estavam doendo nos olhos.

2017-08-25 01:47 UTC, nelsoneldoro commented
Consegui colocar o tslint pra rodar. o/
Review de hoje foi massa.

2017-08-25 03:14 UTC, nelsoneldoro commented
Terminei o filter

2017-08-26 00:34 UTC, danilobjr approved these changes

2017-08-26 00:34 UTC, danilobjr commented on src/pages/index.tsx
> +  handleFilterChange = (event) => {
Pode tipar o event assim: 
```typescript
import {ChangeEvent} from 'react';

// ...

handleFilterChange = (event: ChageEvent<HTMLInputElement>) => {
```

2017-08-26 00:35 UTC, merged